/*
This file is automatically generated
MainPage
C Source
*/

#include "MainPage.h"

extern void Ft_Esd_Noop(void *context);

Ft_Esd_Theme * Ft_Esd_Theme_GetCurrent();
static ft_int16_t MainPage_ESD_Label_Button_X__Property(void *context) { return 255; }
static ft_int16_t MainPage_ESD_Label_Button_Y__Property(void *context) { return 183; }
static ft_int16_t MainPage_ESD_Label_Button_Width__Property(void *context) { return 193; }
static ft_int16_t MainPage_ESD_Label_Button_Font__Property(void *context) { return 31; }
static const char * MainPage_ESD_Label_Button_Text__Property(void *context) { return "Click Me"; }
static ft_int16_t MainPage_ESD3_Label_Font__Property(void *context) { return 31; }
static const char * MainPage_ESD3_Label_Text__Property(void *context) { return "ESD3"; }
static ft_int16_t MainPage_ESD3_Label_X__Property(void *context) { return 12; }
static ft_int16_t MainPage_ESD3_Label_Y__Property(void *context) { return 9; }


void MainPage__Initializer(MainPage *context)
{
	context->Parent = 0;
	Ft_Esd_LabelButton__Initializer(&context->ESD_Label_Button);
	context->ESD_Label_Button.Parent = context;
	context->ESD_Label_Button.X = MainPage_ESD_Label_Button_X__Property;
	context->ESD_Label_Button.Y = MainPage_ESD_Label_Button_Y__Property;
	context->ESD_Label_Button.Width = MainPage_ESD_Label_Button_Width__Property;
	context->ESD_Label_Button.Font = MainPage_ESD_Label_Button_Font__Property;
	context->ESD_Label_Button.Text = MainPage_ESD_Label_Button_Text__Property;
	Ft_Esd_Label__Initializer(&context->ESD3_Label);
	context->ESD3_Label.Parent = context;
	context->ESD3_Label.Font = MainPage_ESD3_Label_Font__Property;
	context->ESD3_Label.Text = MainPage_ESD3_Label_Text__Property;
	context->ESD3_Label.X = MainPage_ESD3_Label_X__Property;
	context->ESD3_Label.Y = MainPage_ESD3_Label_Y__Property;
}

void MainPage_Start(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_LabelButton_Start(&context->ESD_Label_Button);
}

void MainPage_Update(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_LabelButton_Update(&context->ESD_Label_Button);
}

void MainPage_Render(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_LabelButton_Render(&context->ESD_Label_Button);
	Ft_Esd_Label_Render(&context->ESD3_Label);
}

void MainPage_Idle(MainPage *context)
{
	void *parent = context->Parent;
}

void MainPage_End(MainPage *context)
{
	void *parent = context->Parent;
	Ft_Esd_LabelButton_End(&context->ESD_Label_Button);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	MainPage Instance;
} MainPage__ESD;


void *MainPage__Create__ESD()
{
	MainPage__ESD *context = (MainPage__ESD *)malloc(sizeof(MainPage__ESD));
	MainPage__Initializer(&context->Instance);
	context->Instance.Parent = context;
	return context;
}

void MainPage__Destroy__ESD(void *context)
{
	free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
